name: Daily Stock News & Price Update

on:
  schedule:
    - cron: '00 4 * * *'  # Runs daily at 4:00 UTC, which is 9:30 AM IST (UTC+5:30)
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-stock-news-app:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit yfinance requests beautifulsoup4 vaderSentiment

    - name: Run your stock news script
      run: |
        python stock_news_app.py
